from src.core.config.public import *

class user(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    password = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    age = models.FloatField(default=0)
    salary = models.FloatField(default=0)
    ip = models.CharField(max_length=255, null=True, blank=True)
    host = models.CharField(max_length=255, null=True, blank=True)
    date = models.CharField(max_length=255, null=True, blank=True)
    notes = models.CharField(max_length=255, null=True, blank=True)
    image = models.CharField(max_length=255, default="default.png")
    role = models.IntegerField(default=1)
    super = models.BooleanField(default=False)
    mail = models.BooleanField(default=True)
    tasks = models.BooleanField(default=True)
    active = models.BooleanField(default=True)

class mail(models.Model):
    sender = models.IntegerField(default=0)
    receiver = models.IntegerField(default=0)
    title = models.TextField(default="")
    description = models.TextField(default="")
    display_text = models.TextField(default="")
    date = models.CharField(max_length=255, blank=True, null=True)
    remove_sender = models.BooleanField(default=False)
    remove_receiver = models.BooleanField(default=False)
    see_sender = models.BooleanField(default=True)
    see_receiver = models.BooleanField(default=False)
    important_sender = models.BooleanField(default=False)
    star_sender = models.BooleanField(default=False)
    important_receiver = models.BooleanField(default=False)
    star_receiver = models.BooleanField(default=False)

class file(models.Model):
    mail_id = models.IntegerField(default=0)
    task_id = models.IntegerField(default=0)
    name = models.CharField(max_length=255, blank=True, null=True)
    type = models.CharField(max_length=255, blank=True, null=True)
    size = models.CharField(max_length=255, blank=True, null=True)
    link = models.CharField(max_length=255, blank=True, null=True)
    date = models.CharField(max_length=255, blank=True, null=True)

class setting(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=255, null=True, blank=True)
    url = models.CharField(max_length=255, null=True, blank=True)
    language = models.CharField(max_length=255, null=True, blank=True)
    facebook = models.CharField(max_length=255, null=True, blank=True)
    whatsapp = models.CharField(max_length=255, null=True, blank=True)
    twetter = models.CharField(max_length=255, null=True, blank=True)
    telegram = models.CharField(max_length=255, null=True, blank=True)
    youtube = models.CharField(max_length=255, null=True, blank=True)
    instagram = models.CharField(max_length=255, null=True, blank=True)
    linkedin = models.CharField(max_length=255, null=True, blank=True)
    theme = models.CharField(max_length=255, default="dark")
    image = models.CharField(max_length=255, default="default.png")
    enable_bookings = models.BooleanField(default=True)
    enable_notifications = models.BooleanField(default=True)
    enable_registerations = models.BooleanField(default=True)
    deactive = models.BooleanField(default=False)

class project(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    days = models.IntegerField(default=0)
    date = models.CharField(max_length=255, null=True, blank=True)
    finished = models.BooleanField(default=True)
    tasks = models.BooleanField(default=True)
    active = models.BooleanField(default=True)

class task(models.Model):
    project_id = models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    name = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    included = models.TextField(null=True, blank=True)
    rate = models.FloatField(default=0)
    days = models.IntegerField(default=0)
    date = models.CharField(max_length=255, null=True, blank=True)
    finished = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
